### ISSUE TITLE
question: wpconfig.js

### ISSUE THREAD

**Issue by JoshuaJWayne** [6stringbeliever/nuxt_wp#3]
I see that you have moved some of the settings into a wpconfig.js file that is being ignored by your .gitignore file.  

I understand the need to not share your config file however, I am unclear as to what that file is and how to go about using this type of set up on my project.  I am planning on having the wordpress backend on a separate server so the nuxtjs application will not live in the root of the wordpress where the wp-config.php file would be.  Any info on what wpconfig.js looks like and how to set that up would be much appreciated. 

Thank you for spending the time to put together such a clear and complete tutorial on nuxtjs/wp

**Comment by 6stringbeliever** [comment]
Hey, good catch on a little refactor. I'll have to update the posts.

`wpconfig.js` just sits in the root folder and exports a couple variables that are used in the WP library. Mine looks like this:

~~~Javascript
export const WP_SITE_URL = 'http://local.wordpress.dev'
export const WP_HOMEPAGE_LIMIT = 9
~~~

You'd just want to configure `WP_SITE_URL` to wherever your WordPress is installed.

Then, in `lib/wp.js`, instead of doing:

~~~Javascript
...
const wp = new WpApi('http://local.wordpress.dev')

export default wp
~~~

I did this in the repo:

~~~Javascript
...
const wp = new WpApi(WP_SITE_URL)

export default wp
~~~
